[2022-12-16 14:47:32 +0200] [28859] [INFO] Starting gunicorn 20.1.0
[2022-12-16 14:47:32 +0200] [28859] [INFO] Listening at: http://127.0.0.1:8000 (28859)
[2022-12-16 14:47:32 +0200] [28859] [INFO] Using worker: sync
[2022-12-16 14:47:32 +0200] [28860] [INFO] Booting worker with pid: 28860
[2022-12-16 14:47:32 +0200] [28861] [INFO] Booting worker with pid: 28861
[2022-12-16 14:47:32 +0200] [28862] [INFO] Booting worker with pid: 28862
[2022-12-16 14:47:32 +0200] [28863] [INFO] Booting worker with pid: 28863
[2022-12-16 14:47:34 +0200] [28860] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/html/Product-Design-and-Implementation/html/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/html/Product-Design-and-Implementation/html/app.py", line 27, in <module>
    class kuljetusForm(FlaskForm):
  File "/var/www/html/Product-Design-and-Implementation/html/app.py", line 29, in kuljetusForm
    language = SelectField(u'Testing form', choices=[('cpp','C++'), ('py', 'Python')])
NameError: name 'SelectField' is not defined
[2022-12-16 14:47:34 +0200] [28860] [INFO] Worker exiting (pid: 28860)
[2022-12-16 14:47:34 +0200] [28861] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/html/Product-Design-and-Implementation/html/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/html/Product-Design-and-Implementation/html/app.py", line 27, in <module>
    class kuljetusForm(FlaskForm):
  File "/var/www/html/Product-Design-and-Implementation/html/app.py", line 29, in kuljetusForm
    language = SelectField(u'Testing form', choices=[('cpp','C++'), ('py', 'Python')])
NameError: name 'SelectField' is not defined
[2022-12-16 14:47:34 +0200] [28861] [INFO] Worker exiting (pid: 28861)
[2022-12-16 14:47:34 +0200] [28862] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/html/Product-Design-and-Implementation/html/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/html/Product-Design-and-Implementation/html/app.py", line 27, in <module>
    class kuljetusForm(FlaskForm):
  File "/var/www/html/Product-Design-and-Implementation/html/app.py", line 29, in kuljetusForm
    language = SelectField(u'Testing form', choices=[('cpp','C++'), ('py', 'Python')])
NameError: name 'SelectField' is not defined
[2022-12-16 14:47:34 +0200] [28862] [INFO] Worker exiting (pid: 28862)
[2022-12-16 14:47:35 +0200] [28863] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/www/html/Product-Design-and-Implementation/html/wsgi.py", line 1, in <module>
    from app import app
  File "/var/www/html/Product-Design-and-Implementation/html/app.py", line 27, in <module>
    class kuljetusForm(FlaskForm):
  File "/var/www/html/Product-Design-and-Implementation/html/app.py", line 29, in kuljetusForm
    language = SelectField(u'Testing form', choices=[('cpp','C++'), ('py', 'Python')])
NameError: name 'SelectField' is not defined
[2022-12-16 14:47:35 +0200] [28863] [INFO] Worker exiting (pid: 28863)
[2022-12-16 14:47:35 +0200] [28859] [WARNING] Worker with pid 28861 was terminated due to signal 15
--- Logging error ---
Traceback (most recent call last):
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1693, in isEnabledFor
    return self._cache[level]
KeyError: 30

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/logging/__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
    self.log.warning(
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/glogging.py", line 261, in warning
    self.error_log.warning(msg, *args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1454, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1585, in _log
    self.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1595, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1657, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 948, in handle
    self.emit(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1087, in emit
    self.handleError(record)
  File "/usr/lib/python3.9/logging/__init__.py", line 1000, in handleError
    sys.stderr.write('--- Logging error ---\n')
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/var/www/html/Product-Design-and-Implementation/venv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 67, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 231, in run
    super().run()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
    self.log.warning(
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/glogging.py", line 261, in warning
    self.error_log.warning(msg, *args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1453, in warning
    if self.isEnabledFor(WARNING):
  File "/usr/lib/python3.9/logging/__init__.py", line 1695, in isEnabledFor
    _acquireLock()
  File "/usr/lib/python3.9/logging/__init__.py", line 214, in _acquireLock
    def _acquireLock():
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/arbiter.py", line 530, in reap_workers
    self.log.warning(
  File "/var/www/html/Product-Design-and-Implementation/venv/lib/python3.9/site-packages/gunicorn/glogging.py", line 261, in warning
    self.error_log.warning(msg, *args, **kwargs)
Message: 'Worker with pid %s was terminated due to signal %s'
Arguments: (28861, 15)
[2022-12-16 14:47:35 +0200] [28859] [WARNING] Worker with pid 28863 was terminated due to signal 15
[2022-12-16 14:48:05 +0200] [28859] [INFO] Shutting down: Master
[2022-12-16 14:48:05 +0200] [28859] [INFO] Reason: Worker failed to boot.
